<?php

namespace Database\Seeders;

use App\Models\Page;
use Illuminate\Database\Seeder;

class PageSeeder extends Seeder
{
    public function run(): void
    {
        $pages = [
            [
                'title' => 'X-Buy Buyer Protection Guarantee',
                'slug' => 'buyer-protection',
                'content' => '<h1>X-Buy Buyer Protection Guarantee</h1><p>At X-Buy, buyer trust is the foundation of our peer-to-peer electronics marketplace. Every single purchase on X-Buy is automatically backed by our 100% Escrow Buyer Protection.</p><h2>1. 100% Escrow Protection</h2><p>When you checkout on X-Buy, your payment is safely held in our regulated escrow holding account powered by Razorpay. The seller is never paid upfront. Funds remain locked in escrow while the package is processed, shipped, delivered, and tested.</p><h2>2. 7-Day Testing Window</h2><p>From the exact moment your shipment is marked delivered by the courier, your 7-day hardware inspection window begins. We encourage you to run stress tests (such as Furmark, 3DMark, Cinebench, or MemTest86) to confirm thermals, clock speeds, and stability.</p><h2>3. When Are You Eligible for a Full Refund?</h2><ul><li>The item received is functionally defective or damaged during transit.</li><li>The item does not match the seller description, specifications, or cosmetic grade.</li><li>The serial number does not match the listing verification photos.</li><li>The item does not arrive within the guaranteed carrier delivery timeframe.</li></ul><h2>4. How to Claim</h2><p>Simply navigate to <strong>My Orders</strong> in your dashboard and click <strong>Raise Dispute</strong> before your 7-day inspection window ends. This instantly freezes the escrow release while our arbitration team reviews your evidence.</p>',
                'meta_title' => 'Buyer Protection Guarantee | X-Buy Escrow',
                'meta_description' => 'Learn how X-Buy protects your money with 7-day testing windows and 100% escrow protection.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'Seller Protection & Payouts',
                'slug' => 'seller-guidelines',
                'content' => '<h1>Seller Guidelines & Protection</h1><p>X-Buy is built to give genuine computer hardware sellers a secure, transparent platform with 0% hidden fee surprises and guaranteed protection against fraudulent returns.</p><h2>1. Accurate Component Listings</h2><p>Sellers must specify correct category tags, brand mappings, model numbers, and grading criteria. All cosmetic defects, missing original boxes, and accessories must be disclosed.</p><h2>2. 48-Hour Dispatch Standard</h2><p>Upon receiving order notification, sellers must package the item securely and dispatch via the approved Shiprocket prepaid label within 48 hours. Orders not shipped within 72 hours are subject to automatic escrow cancellation.</p><h2>3. Anti-Fraud Seller Protection</h2><p>We protect sellers by requiring buyers to submit unboxing video evidence and benchmark logs before any return or dispute can be approved. If a buyer returns a damaged or substituted component, X-Buy seller insurance reimburses the full payout amount.</p><h2>4. Direct Bank Settlements</h2><p>Upon buyer confirmation or expiration of the 7-day testing period without dispute, payout is immediately released to your registered bank account or UPI ID with zero withdrawal fees.</p>',
                'meta_title' => 'Seller Protection & Guidelines | X-Buy',
                'meta_description' => 'Rules, dispatch standards, and insurance protections for selling PC parts on X-Buy.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'Escrow Financial Operations Policy',
                'slug' => 'escrow-policy',
                'content' => '<h1>Escrow Financial Operations Policy</h1><p>This policy details the financial mechanics governing transactional fund custody on X-Buy.in.</p><h2>1. Fund Custody & Razorpay Escrow</h2><p>All buyer payments are captured into dedicated nodal escrow accounts operated in compliance with Reserve Bank of India (RBI) guidelines. X-Buy does not utilize transactional funds for working capital.</p><h2>2. Step-by-Step Fund Flow</h2><ol><li><strong>Checkout & Capture:</strong> Buyer completes payment via UPI, Debit/Credit card, NetBanking, or X-Buy Wallet. Total order sum is locked in Escrow.</li><li><strong>Courier Transit:</strong> Funds remain frozen during door-to-door transit via Shiprocket logistics.</li><li><strong>7-Day Inspection:</strong> Upon delivery confirmation, buyer has 7 full calendar days to benchmark hardware.</li><li><strong>Settlement:</strong> Buyer confirms delivery or timer expires. Platform commission is deducted and net proceeds are disbursed via NEFT/IMPS/UPI.</li></ol><h2>3. Dispute Freezes</h2><p>If a dispute is raised within the 7-day window, the automated payout clock is frozen immediately until both parties reach resolution or X-Buy arbitration issues a ruling.</p>',
                'meta_title' => 'Escrow Financial Policy | X-Buy',
                'meta_description' => 'Understand how buyer funds are securely held in RBI-compliant escrow until hardware inspection completes.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'Prohibited Items & Safety Guidelines',
                'slug' => 'safety-guidelines',
                'content' => '<h1>Prohibited Items & Platform Safety</h1><p>To preserve community trust and comply with statutory requirements, the following items and practices are strictly prohibited on X-Buy.</p><h2>1. Prohibited Items</h2><ul><li>Counterfeit, cloned, or remarket-etched chips (e.g. fake GPUs with modified VBIOS).</li><li>Stolen computer hardware or devices with locked BIOS/MDM profiles.</li><li>Hazardous materials, cracked lithium batteries, or leaking liquid coolers.</li><li>Weapons, narcotics, or non-computer merchandise.</li></ul><h2>2. Off-Platform Transactions (Zero Tolerance)</h2><p>Attempting to bypass X-Buy escrow by requesting direct UPI, Google Pay, or cash on delivery outside the platform is strictly forbidden and results in immediate permanent account termination and forfeiture of wallet balances.</p>',
                'meta_title' => 'Safety & Prohibited Items | X-Buy',
                'meta_description' => 'Read X-Buy safety guidelines and banned product categories.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'Hardware Authentication Guide',
                'slug' => 'authenticate',
                'content' => '<h1>Hardware Authentication & Anti-Counterfeit Guide</h1><p>Counterfeit graphics cards, re-flashed BIOS chips, and remarked CPUs exist in the secondary market. Here is how X-Buy verifies authenticity.</p><h2>1. Serial Number Cross-Checking</h2><p>Sellers are required to upload high-resolution photographs of the PCB serial number sticker, manufacturer barcode, and original retail box. Our automated moderation checks serial formatting against manufacturer registries.</p><h2>2. Buyer Verification Checklist</h2><ul><li><strong>GPU-Z Verification:</strong> Download official TechPowerUp GPU-Z. Verify subvendor, shader count, and die size match reference specifications.</li><li><strong>Furmark & 3DMark Benchmark:</strong> Check clock speeds and temperature curves under 100% load.</li><li><strong>CPU-Z & HWMonitor:</strong> Verify core counts, cache sizes, and architecture revisions.</li></ul>',
                'meta_title' => 'Hardware Authentication Guide | X-Buy',
                'meta_description' => 'How to verify genuine GPUs, CPUs, and motherboard serial numbers on X-Buy.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'Shipping Made Easy',
                'slug' => 'shipping',
                'content' => '<h1>Shipping Made Easy with Shiprocket</h1><p>X-Buy partners with Shiprocket to provide seamless, insured door-to-door delivery across 24,000+ pincodes in India.</p><h2>1. Prepaid Automated Shipping Labels</h2><p>Sellers do not need to negotiate courier rates. Once an order is placed, click <strong>Generate Label</strong> in your dashboard to download a printable barcode label with tracking metadata.</p><h2>2. Scheduled Doorstep Pickup</h2><p>Logistics partners (Bluedart, Delhivery, DTDC, Xpressbees) will arrive at the seller address for parcel pickup within 24 business hours.</p><h2>3. Live GPS Tracking & Insurance</h2><p>Both buyer and seller receive live SMS and in-app tracking alerts at every stage of the transit. Every shipment is covered by transit insurance up to ₹1,00,000.</p>',
                'meta_title' => 'Shipping Made Easy | X-Buy Logistics',
                'meta_description' => 'Insured shipping, prepaid shipping labels, and doorstep pickup powered by Shiprocket.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'Packaging Best Practices for PC Hardware',
                'slug' => 'packaging',
                'content' => '<h1>Packaging Best Practices for Electronics</h1><p>Delicate electronics like graphics cards, motherboards, and processors require meticulous packaging to prevent electrostatic discharge (ESD) and transit impacts.</p><h2>1. Anti-Static Bags are Mandatory</h2><p>Never wrap bare GPUs, motherboards, or RAM sticks in ordinary bubble wrap or newspaper. Always place the component in a silver or pink anti-static (ESD) shielding bag first.</p><h2>2. The "Double Box" Method</h2><p>Place the anti-static wrapped item inside its retail box or a sturdy inner carton with at least 2 inches of cushioning on all sides. Place that box inside an outer heavy-duty corrugated shipping box.</p><h2>3. CPU Socket Protection</h2><p>For Intel (LGA) and modern AMD (AM5) motherboards, the plastic socket protective cover must always be installed to prevent bent pins during transit.</p>',
                'meta_title' => 'Packaging Best Practices | X-Buy',
                'meta_description' => 'Essential guidelines for packaging GPUs, CPUs, and motherboards safely for courier transit.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'Refunds & Returns Policy',
                'slug' => 'refund-policy',
                'content' => '<h1>Refunds and Returns Policy</h1><p>Our refund process is designed to be fair, swift, and transparent for both parties.</p><h2>1. Inspection Window Eligibility</h2><p>Returns can be initiated within the 7-day inspection window if the item is verified as defective or materially different from the listing description.</p><h2>2. Return Shipping Process</h2><p>Upon dispute approval, X-Buy generates a prepaid return shipping label. Once the seller receives the returned component and verifies serial integrity, the escrow fund is released as a 100% refund to the buyer original payment method within 3 to 5 banking days.</p><h2>3. Buyer Remorse Limitations</h2><p>Because X-Buy is a peer-to-peer marketplace, subjective change-of-mind returns are not permitted once the item matches the listed description and functions properly.</p>',
                'meta_title' => 'Refunds & Returns Policy | X-Buy',
                'meta_description' => 'Step-by-step return label generation and 7-day dispute arbitration rules.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'How Payouts Work',
                'slug' => 'getting-paid',
                'content' => '<h1>How Seller Payouts Work</h1><p>Getting paid on X-Buy is automatic, reliable, and completely free of transfer charges.</p><h2>1. Payout Calculation</h2><p>Your net earnings are calculated as: <code>Net Payout = Item Price - Platform Commission</code>. The buyer covers shipping charges.</p><h2>2. Settlement Triggers</h2><p>Payout is initiated immediately when: (a) the buyer confirms satisfaction by clicking "Confirm Delivery & Release Funds"; or (b) the 7-day testing window expires without an open dispute.</p><h2>3. Bank Transfer Timelines</h2><p>Direct bank deposits (NEFT/IMPS) are dispatched within 24 hours of release. UPI payouts are instant.</p>',
                'meta_title' => 'How Payouts Work | X-Buy',
                'meta_description' => 'Direct bank deposits, zero transfer fees, and payout release timelines.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'Coupons & Promotional Terms',
                'slug' => 'coupons-and-promotions',
                'content' => '<h1>Coupons & Promotion Terms</h1><p>X-Buy regularly releases promotional vouchers to celebrate major tech launches and holiday seasons.</p><h2>1. Applying Discount Codes</h2><p>Enter your promo code (e.g. <code>XBUY10</code> or <code>FIRSTBUY</code>) in the cart drawer or checkout accordion. The discount is applied immediately to your subtotal.</p><h2>2. Terms of Use</h2><p>Coupons are non-transferable, cannot be redeemed for cash, and cannot be stacked with multiple promotional discounts unless explicitly specified.</p>',
                'meta_title' => 'Coupons & Promotions | X-Buy',
                'meta_description' => 'Promo discount codes and voucher terms on X-Buy.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'Contact Customer Support',
                'slug' => 'contact-us',
                'content' => '<h1>Contact Customer Support</h1><p>Our dedicated support team is here to assist with escrow queries, shipping logistics, seller onboarding, and dispute arbitration.</p><h2>Customer Support Channels</h2><p><strong>Email:</strong> support@x-buy.in<br><strong>Hours:</strong> Monday to Saturday, 9:00 AM - 8:00 PM IST<br><strong>Typical Response:</strong> Under 2 hours during business operations.</p><p>For active orders, please navigate to your dashboard to submit an order-specific ticket with one click.</p>',
                'meta_title' => 'Contact Us | X-Buy Support',
                'meta_description' => 'Get in touch with X-Buy customer support and escrow mediation team.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'Help Center & Frequently Asked Questions',
                'slug' => 'faqs',
                'content' => '<h1>Help Center & Frequently Asked Questions</h1><h2>1. How does the escrow process work?</h2><p>Escrow is a financial agreement where X-Buy holds the buyer payment in a secure nodal account until the product is delivered and tested. Once the buyer verifies the part or the 7-day testing window expires, the payment is securely transferred to the seller.</p><h2>2. What happens if an item is defective?</h2><p>If hardware crashes or fails benchmarks during the 7-day testing window, click "Raise Dispute" in your order details. The funds will be held while our team reviews the evidence and issues a return shipping label.</p><h2>3. How much does X-Buy charge?</h2><p>Buyers pay a nominal ₹85 Buyer Protection fee. Sellers pay a competitive platform commission between 3% to 5% depending on the component category.</p><h2>4. Can I cancel my order?</h2><p>Buyers can cancel an order anytime before the seller prints the shipping label and marks dispatch. After dispatch, cancellation is not possible.</p>',
                'meta_title' => 'Help Center & FAQ | X-Buy',
                'meta_description' => 'Frequently asked questions about X-Buy escrow, shipping, returns, and testing.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'Platform & Gateway Service Status',
                'slug' => 'service-status',
                'content' => '<h1>Platform & Gateway Service Status</h1><p>Real-time operational status of all X-Buy platform infrastructure and integration partners.</p><h2>Current System Health</h2><ul><li><strong>X-Buy Core Marketplace:</strong> <span style="color: green; font-weight: bold;">Operational (99.98% Uptime)</span></li><li><strong>Razorpay Escrow Gateway:</strong> <span style="color: green; font-weight: bold;">Operational</span></li><li><strong>Shiprocket Courier Dispatch:</strong> <span style="color: green; font-weight: bold;">Operational</span></li><li><strong>SMS & Email Verification OTP:</strong> <span style="color: green; font-weight: bold;">Operational</span></li></ul>',
                'meta_title' => 'Service Status | X-Buy',
                'meta_description' => 'Live uptime and system status for Razorpay, Shiprocket, and X-Buy services.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'How X-Buy Works',
                'slug' => 'how-it-works',
                'content' => '<h1>How X-Buy Works</h1><p>Buying and selling computer components has never been safer. Here is our 3-step community workflow:</p><h2>1. Discover Verified Gear</h2><p>Browse thousands of pre-owned and refurbished graphics cards, CPUs, and PC accessories. Every listing displays accurate condition grades and original photos.</p><h2>2. Safe Escrow Checkout</h2><p>Pay securely using UPI, cards, or wallet credits. Your money is locked in Escrow and is not given to the seller upfront.</p><h2>3. 7-Day Stress-Test & Release</h2><p>Receive your package via insured courier. Benchmark and stress-test the hardware for 7 full days. Once you confirm satisfaction, the seller gets paid.</p>',
                'meta_title' => 'How X-Buy Works | 3-Step Escrow Process',
                'meta_description' => 'Simple 3-step guide to buying and selling PC parts securely on X-Buy.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'Hot Deals & Price Drops',
                'slug' => 'deals',
                'content' => '<h1>Hot Deals & Price Drops</h1><p>Explore exclusive hardware listings with price reductions of 20% or more compared to current retail prices.</p><p>Check back daily for flash sales, discounted custom gaming rigs, and high-performance pre-owned hardware from verified community sellers.</p>',
                'meta_title' => 'Hot Deals & Hardware Price Drops | X-Buy',
                'meta_description' => 'Discover deep discounts on verified graphics cards, processors, and PC components.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'Gift Cards & Wallet Credits',
                'slug' => 'gift-card-exchange',
                'content' => '<h1>X-Buy Wallet & Credits</h1><p>Manage your account balances, redeem promotional gift cards, and spend your marketplace earnings seamlessly.</p><h2>1. Internal Wallet Utility</h2><p>Your X-Buy Wallet holds seller payout balances and dispute refund credits. Wallet funds can be withdrawn directly to your bank account anytime or applied instantly during checkout with one click.</p><h2>2. Instant Balance Application</h2><p>At checkout, simply check "Use X-Buy Wallet Balance" to deduct your credit balance from the total order amount.</p>',
                'meta_title' => 'Wallet & Credits | X-Buy',
                'meta_description' => 'How to manage your X-Buy internal wallet balance and redeem credits.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'About X-Buy Marketplace',
                'slug' => 'about-us',
                'content' => '<h1>About X-Buy Marketplace</h1><p>X-Buy was founded in 2026 with a singular, resolute mission: to eliminate scams and build the ultimate community marketplace for computer hardware in India.</p><p>For years, buying and selling second-hand PC parts meant risky bank transfers on forums, meeting strangers in parking lots, and fearing dead-on-arrival (DOA) hardware with zero recourse.</p><p>X-Buy solves this permanently through 100% Escrow Protection, insured door-to-door courier logistics, and mandatory 7-day testing windows. Today, thousands of gamers, content creators, and PC builders trust X-Buy to power their dream setups safely.</p>',
                'meta_title' => 'About Us | X-Buy Story & Ethos',
                'meta_description' => 'Learn how X-Buy is transforming the pre-owned computer hardware market with escrow trust.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'Careers at X-Buy',
                'slug' => 'careers',
                'content' => '<h1>Careers at X-Buy</h1><p>We are a high-velocity team of hardware enthusiasts, software engineers, and customer advocates building the future of peer-to-peer commerce.</p><h2>Open Opportunities</h2><ul><li><strong>Full-Stack Laravel / Vue / React Engineers</strong> (Bangalore / Remote)</li><li><strong>Hardware Authentication Specialists</strong> (Bangalore Bench Lab)</li><li><strong>Customer Experience & Trust Arbitration Specialists</strong> (Remote)</li></ul><p>Send your portfolio and resume to <code>careers@xbuy.in</code>.</p>',
                'meta_title' => 'Careers at X-Buy | Join Our Team',
                'meta_description' => 'Join the engineering, product, and operations team at X-Buy.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'Terms of Service',
                'slug' => 'terms-of-service',
                'content' => '<h1>Terms of Service</h1><p>These Terms of Service constitute a legally binding agreement between you and X-Buy Technologies Pvt Ltd regarding your use of the website, mobile services, and escrow infrastructure.</p><h2>1. User Accounts</h2><p>You must provide accurate, verifiable identity details. Impersonation, fake accounts, or multiple accounts created to circumvent suspensions are strictly prohibited.</p><h2>2. Transactional Covenant</h2><p>All buying and selling must transpire exclusively through the X-Buy platform. Any attempt to transact off-platform voids all guarantees and triggers immediate account termination.</p><h2>3. Governing Law</h2><p>These Terms are governed by and construed in accordance with the laws of India, under jurisdiction of competent courts in Bangalore, Karnataka.</p>',
                'meta_title' => 'Terms of Service | X-Buy',
                'meta_description' => 'Read our user terms, account covenants, and transactional policies.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'Privacy Policy',
                'slug' => 'privacy-policy',
                'content' => '<h1>Privacy Policy</h1><p>X-Buy is committed to the protection of your personal and transactional information under the Digital Personal Data Protection Act (DPDP) and GDPR standards.</p><h2>1. Information We Collect</h2><p>We collect essential identity, contact, shipping address, and device metadata required to process orders, verify KYC integrity, and coordinate courier deliveries.</p><h2>2. Data Security & Storage</h2><p>All sensitive information, passwords, and tokens are encrypted at rest using industry-standard AES-256 and hashed via modern cryptographic algorithms. We never store raw credit card numbers.</p>',
                'meta_title' => 'Privacy Policy | X-Buy',
                'meta_description' => 'Read how X-Buy collects, encrypts, and protects your personal information.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'Cookie Preferences Manager',
                'slug' => 'cookie-preferences',
                'content' => '<h1>Cookie Preferences Manager</h1><p>X-Buy uses cookies to ensure our website functions smoothly, keep you signed in, remember your cart items, and analyze traffic patterns.</p><h2>1. Strictly Necessary Cookies</h2><p>Required for basic site navigation, authentication tokens, and shopping cart persistence. These cannot be disabled.</p><h2>2. Analytics & Performance Cookies</h2><p>Help us understand page load speeds and visitor flow so we can optimize your marketplace experience.</p>',
                'meta_title' => 'Cookie Preferences | X-Buy',
                'meta_description' => 'Manage your cookie tracking settings on X-Buy.',
                'is_active' => true,
                'is_protected' => true,
            ],
            [
                'title' => 'Licenses & Commercial Disclosures',
                'slug' => 'licenses-and-disclosures',
                'content' => '<h1>Legal Licenses & Disclosures</h1><p>Corporate registry, commercial license details, and payment facilitator compliance information for X-Buy Technologies Pvt Ltd.</p><ul><li><strong>Corporate Identity Number (CIN):</strong> U72900KA2026PTC184920</li><li><strong>Registered Office:</strong> Bangalore, Karnataka, India - 560001</li><li><strong>Escrow Gateway Partner:</strong> Razorpay Software Private Limited (RBI Authorized Payment Aggregator)</li><li><strong>Logistics Network Partner:</strong> Shiprocket (BigFoot Retail Solutions Pvt Ltd)</li></ul>',
                'meta_title' => 'Licenses & Disclosures | X-Buy',
                'meta_description' => 'Corporate registry numbers and payment compliance disclosures.',
                'is_active' => true,
                'is_protected' => true,
            ]
        ];

        foreach ($pages as $page) {
            Page::updateOrCreate(['slug' => $page['slug']], $page);
        }
    }
}
