<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Dispute;
use App\Models\Escrow;
use App\Models\Listing;
use App\Models\Order;
use App\Models\Rating;
use App\Models\Shipment;
use App\Models\Wishlist;
use App\Models\SupportTicket;
use App\Models\SiteSetting;
use App\Models\Notification;
use Carbon\Carbon;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

class BuyerController extends Controller
{
    /**
     * Get buyer orders.
     */
    public function getOrders(Request $request): JsonResponse
    {
        $orders = Order::with(['listing.images', 'seller'])
            ->where('buyer_id', $request->user()->id)
            ->orderBy('created_at', 'desc')
            ->paginate($request->input('per_page', 10));

        return $this->successResponse($orders, 'Orders retrieved successfully');
    }

    /**
     * Get single order details.
     */
    public function getOrder(int $id, Request $request): JsonResponse
    {
        $order = Order::with(['listing.images', 'seller', 'escrow', 'shipment', 'dispute.responses.user', 'rating'])
            ->where('buyer_id', $request->user()->id)
            ->where('id', $id)
            ->first();

        if (!$order) {
            return $this->errorResponse('Order not found', 404);
        }

        return $this->successResponse($order, 'Order details retrieved successfully');
    }

    /**
     * Create a new order.
     */
    public function createOrder(Request $request): JsonResponse
    {
        $validator = Validator::make($request->all(), [
            'listing_id' => 'required|exists:listings,id',
            'delivery_address' => 'required|array',
            'delivery_address.name' => 'required|string',
            'delivery_address.phone' => 'required|string',
            'delivery_address.street' => 'required|string',
            'delivery_address.city' => 'required|string',
            'delivery_address.state' => 'required|string',
            'delivery_address.pincode' => 'required|string|max:10',
        ]);

        if ($validator->fails()) {
            return $this->errorResponse('Validation error', 422, $validator->errors());
        }

        $listing = Listing::with('seller')->find($request->input('listing_id'));

        // Check if listing is active
        if ($listing->listing_status !== 'active') {
            return $this->errorResponse('Listing is not available for purchase.', 400);
        }

        // Check if buyer is not the seller
        if ($listing->seller->user_id === $request->user()->id) {
            return $this->errorResponse('You cannot buy your own listing.', 400);
        }

        // Check if listing is restricted to trusted/verified buyers only
        if ($listing->trusted_buyers_only && $request->user()->buyer_badge === 'new_buyer') {
            return $this->errorResponse('This seller requires Verified Buyer status. Complete 5+ purchases to unlock.', 400);
        }

        // Calculate pricing
        $productAmount = $listing->price;
        $shippingAmount = $listing->shipping_charges;
        $totalAmount = $productAmount + $shippingAmount;
        $commissionPercent = $listing->commission_rate;
        $commissionAmount = round(($productAmount * $commissionPercent) / 100, 2);
        $sellerPayoutAmount = $productAmount - $commissionAmount;

        // Order number auto-generated by Order model via OrderNumberService
        // Mock Razorpay Order Creation
        $razorpayOrderId = 'order_' . Str::random(14);

        $order = Order::create([
            'listing_id'             => $listing->id,
            'buyer_id'               => $request->user()->id,
            'seller_id'              => $listing->seller_id,
            'product_amount'         => $productAmount,
            'shipping_amount'        => $shippingAmount,
            'total_amount'           => $totalAmount,
            'commission_percent'     => $commissionPercent,
            'commission_amount'      => $commissionAmount,
            'seller_payout_amount'   => $sellerPayoutAmount,
            'razorpay_order_id'      => $razorpayOrderId,
            'order_status'           => 'pending_payment',
            'delivery_address'       => $request->input('delivery_address'),
            'testing_window_days'    => $listing->testing_window_days,
            'warranty_terms_snapshot' => [
                'manufacturer_warranty_status'  => $listing->manufacturer_warranty_status,
                'manufacturer_warranty_months'  => $listing->manufacturer_warranty_months,
                'seller_warranty_months'        => $listing->seller_warranty_months,
                'document_status'               => $listing->document_status,
            ],
        ]);


        return $this->successResponse($order, 'Order created successfully. Please proceed with payment.', 201);
    }

    /**
     * Mock / Real Payment Endpoint.
     */
    public function payOrder(int $id, Request $request): JsonResponse
    {
        $order = Order::where('buyer_id', $request->user()->id)
            ->where('id', $id)
            ->where('order_status', 'pending_payment')
            ->first();

        if (!$order) {
            return $this->errorResponse('Order not found or already paid', 404);
        }

        $validator = Validator::make($request->all(), [
            'razorpay_payment_id' => 'required|string',
            'razorpay_signature' => 'required|string',
        ]);

        if ($validator->fails()) {
            return $this->errorResponse('Validation error', 422, $validator->errors());
        }

        DB::transaction(function () use ($order, $request) {
            // Update listing status
            $order->listing->update([
                'listing_status' => 'sold',
                'sold_at' => Carbon::now(),
            ]);

            // Update order
            $order->update([
                'order_status' => 'payment_received',
                'razorpay_payment_id' => $request->input('razorpay_payment_id'),
            ]);

            // Create Escrow
            Escrow::create([
                'order_id' => $order->id,
                'amount_held' => $order->product_amount,
                'seller_amount' => $order->seller_payout_amount,
                'commission_amount' => $order->commission_amount,
                'status' => 'held',
                'payout_status' => 'pending',
                'warranty_days' => $order->testing_window_days,
            ]);

            // Create Shipment skeleton
            Shipment::create([
                'order_id' => $order->id,
                'status' => 'pending',
            ]);

            // Send dynamic emails
            Notification::sendSystemMail($order->buyer, 'payment_success', [
                'buyer_name' => $order->buyer->name,
                'order_number' => $order->order_number,
                'order_amount' => $order->total_amount,
                'product_title' => $order->listing->title,
                'seller_shop_name' => $order->seller->shop_name,
            ]);

            Notification::sendSystemMail($order->seller->user, 'escrow_hold', [
                'seller_name' => $order->seller->user->name,
                'buyer_name' => $order->buyer->name,
                'order_number' => $order->order_number,
                'product_title' => $order->listing->title,
                'seller_payout_amount' => $order->seller_payout_amount,
                'testing_days' => $order->testing_window_days,
            ]);
        });

        return $this->successResponse($order->fresh(), 'Payment verified and escrow locked successfully');
    }

    /**
     * Get buyer wishlist.
     */
    public function getWishlist(Request $request): JsonResponse
    {
        $wishlists = Wishlist::with('listing.images')
            ->where('user_id', $request->user()->id)
            ->paginate($request->input('per_page', 10));

        return $this->successResponse($wishlists, 'Wishlist retrieved successfully');
    }

    /**
     * Toggle item in wishlist.
     */
    public function toggleWishlist(Request $request): JsonResponse
    {
        $validator = Validator::make($request->all(), [
            'listing_id' => 'required|exists:listings,id',
        ]);

        if ($validator->fails()) {
            return $this->errorResponse('Validation error', 422, $validator->errors());
        }

        $listingId = $request->input('listing_id');
        $userId = $request->user()->id;

        $wishlist = Wishlist::where('user_id', $userId)
            ->where('listing_id', $listingId)
            ->first();

        if ($wishlist) {
            $wishlist->delete();
            // Decrement wishlist count on listing
            Listing::find($listingId)->decrement('wishlist_count');
            return $this->successResponse(null, 'Listing removed from wishlist');
        } else {
            $listing = Listing::find($listingId);
            Wishlist::create([
                'user_id' => $userId,
                'listing_id' => $listingId,
                'price_at_wishlist' => $listing->price,
            ]);
            // Increment wishlist count on listing
            $listing->increment('wishlist_count');
            return $this->successResponse(null, 'Listing added to wishlist');
        }
    }

    /**
     * Add item to wishlist.
     */
    public function addToWishlist(int $listingId, Request $request): JsonResponse
    {
        $listing = Listing::find($listingId);
        if (!$listing) {
            return $this->errorResponse('Listing not found', 404);
        }

        $userId = $request->user()->id;
        $exists = Wishlist::where('user_id', $userId)->where('listing_id', $listingId)->exists();

        if (!$exists) {
            Wishlist::create([
                'user_id' => $userId,
                'listing_id' => $listingId,
                'price_at_wishlist' => $listing->price,
            ]);
            $listing->increment('wishlist_count');
        }

        return $this->successResponse(null, 'Listing added to wishlist');
    }

    /**
     * Remove item from wishlist.
     */
    public function removeFromWishlist(int $listingId, Request $request): JsonResponse
    {
        $listing = Listing::find($listingId);
        if (!$listing) {
            return $this->errorResponse('Listing not found', 404);
        }

        $userId = $request->user()->id;
        $wishlist = Wishlist::where('user_id', $userId)->where('listing_id', $listingId)->first();

        if ($wishlist) {
            $wishlist->delete();
            $listing->decrement('wishlist_count');
        }

        return $this->successResponse(null, 'Listing removed from wishlist');
    }

    /**
     * Confirm delivery (accept order manually).
     */
    public function confirmDelivery(int $id, Request $request): JsonResponse
    {
        $order = Order::where('buyer_id', $request->user()->id)
            ->where('id', $id)
            ->first();

        if (!$order) {
            return $this->errorResponse('Order not found', 404);
        }

        if (!$order->can_accept) {
            return $this->errorResponse('Order cannot be completed at this stage.', 400);
        }

        DB::transaction(function () use ($order) {
            $order->update([
                'order_status' => 'completed',
                'completed_at' => Carbon::now(),
            ]);

            // Release escrow
            if ($order->escrow) {
                $order->escrow->update([
                    'status' => 'released',
                    'released_at' => Carbon::now(),
                ]);
            }

            // Update user completed orders count
            $order->buyer->increment('completed_orders_count');
            $order->seller->user->increment('completed_orders_count');

            // Recalculate buyer badge
            \App\Jobs\BuyerBadgeJob::dispatch($order->buyer_id);

            // Recalculate seller badge
            \App\Jobs\BadgeCalculationJob::dispatch($order->seller_id);
        });

        return $this->successResponse($order->fresh(), 'Order completed and escrow released to seller.');
    }

    /**
     * Raise a dispute.
     */
    public function raiseDispute(int $id, Request $request): JsonResponse
    {
        $order = Order::where('buyer_id', $request->user()->id)
            ->where('id', $id)
            ->first();

        if (!$order) {
            return $this->errorResponse('Order not found', 404);
        }

        if (!$order->can_dispute) {
            return $this->errorResponse('Dispute cannot be raised at this stage.', 400);
        }

        $validator = Validator::make($request->all(), [
            'dispute_type' => 'required|in:item_not_as_described,item_not_working,fake_counterfeit,shipping_delay,packaging_damage,other',
            'description' => 'required|string',
            'evidence_images' => 'nullable|array',
            'evidence_images.*' => 'string', // URLs or file paths
        ]);

        if ($validator->fails()) {
            return $this->errorResponse('Validation error', 422, $validator->errors());
        }

        DB::transaction(function () use ($order, $request) {
            $order->update([
                'order_status' => 'disputed',
            ]);

            $dispute = Dispute::create([
                'order_id' => $order->id,
                'buyer_id' => $order->buyer_id,
                'seller_id' => $order->seller_id,
                'dispute_type' => $request->input('dispute_type'),
                'description' => $request->input('description'),
                'evidence_images' => $request->input('evidence_images', []),
                'status' => 'open',
                'seller_response_deadline' => Carbon::now()->addHours(48),
            ]);

            // Trigger for Buyer raises dispute on 3+ orders in 30 days
            $thirtyDaysAgo = Carbon::now()->subDays(30);
            $disputedOrdersCount = Dispute::where('buyer_id', $order->buyer_id)
                ->where('created_at', '>=', $thirtyDaysAgo)
                ->count();
            if ($disputedOrdersCount >= 3) {
                \App\Models\FraudFlag::firstOrCreate(
                    [
                        'flag_type' => 'suspicious_buyer_pattern',
                        'flagged_user_id' => $order->buyer_id,
                        'status' => 'pending'
                    ],
                    [
                        'details' => [
                            'buyer_id' => $order->buyer_id,
                            'disputed_orders_count_last_30_days' => $disputedOrdersCount,
                        ]
                    ]
                );
            }

            // Notify admin
            \App\Models\Notification::notifyAdmins(
                'New Dispute Raised',
                "Buyer Customer has raised a dispute on Order #{$order->order_number} due to: " . ucfirst(str_replace('_', ' ', $request->input('dispute_type'))),
                'dispute',
                'dispute',
                $dispute->id
            );

            // Hold escrow status update (already held, but we can verify)
            if ($order->escrow) {
                $order->escrow->update([
                    'status' => 'disputed',
                ]);
            }
        });

        return $this->successResponse($order->fresh(), 'Dispute raised successfully. Seller has 48 hours to respond.');
    }

    /**
     * Rate the seller.
     */
    public function rateSeller(int $id, Request $request): JsonResponse
    {
        $order = Order::where('buyer_id', $request->user()->id)
            ->where('id', $id)
            ->first();

        if (!$order) {
            return $this->errorResponse('Order not found', 404);
        }

        if (!$order->can_rate) {
            return $this->errorResponse('You cannot rate the seller for this order yet, or you already rated them.', 400);
        }

        $validator = Validator::make($request->all(), [
            'communication_rating' => 'required|integer|between:1,5',
            'shipping_rating' => 'required|integer|between:1,5',
            'description_rating' => 'required|integer|between:1,5',
            'comment' => 'nullable|string|max:1000',
        ]);

        if ($validator->fails()) {
            return $this->errorResponse('Validation error', 422, $validator->errors());
        }

        $comm = $request->input('communication_rating');
        $ship = $request->input('shipping_rating');
        $desc = $request->input('description_rating');
        $weightedTotal = round(($comm * 0.2) + ($ship * 0.3) + ($desc * 0.5), 2);

        $rating = Rating::create([
            'order_id' => $order->id,
            'seller_id' => $order->seller_id,
            'buyer_id' => $order->buyer_id,
            'communication_rating' => $comm,
            'shipping_rating' => $ship,
            'description_rating' => $desc,
            'weighted_total' => $weightedTotal,
            'comment' => $request->input('comment'),
        ]);

        return $this->successResponse($rating, 'Rating submitted successfully');
    }

    /**
     * Create a support ticket.
     */
    public function createTicket(Request $request): JsonResponse
    {
        $validator = Validator::make($request->all(), [
            'subject' => 'required|string|max:255',
            'message' => 'required|string|max:5000',
        ]);

        if ($validator->fails()) {
            return $this->errorResponse('Validation error', 422, $validator->errors());
        }

        $ticket = SupportTicket::create([
            'user_id' => $request->user()->id,
            'subject' => $request->input('subject'),
            'message' => $request->input('message'),
            'status' => 'open',
        ]);

        // Email Notification to Admin
        if (SiteSetting::getVal('ticket_email_notifications_enabled', '1') == '1') {
            $adminEmail = SiteSetting::getVal('ticket_admin_email', 'contact@x-buy.in');
            try {
                \Illuminate\Support\Facades\Mail::to($adminEmail)->send(
                    new \App\Mail\SupportTicketRaised($ticket, $request->user()->name, $request->user()->email)
                );
            } catch (\Exception $e) {
                \Illuminate\Support\Facades\Log::error("Failed to send ticket email notification: " . $e->getMessage());
            }
        }

        // WhatsApp Notification trigger (mock / logger)
        if (SiteSetting::getVal('ticket_whatsapp_notifications_enabled', '0') == '1') {
            $waNumber = SiteSetting::getVal('ticket_whatsapp_number');
            if ($waNumber) {
                \Illuminate\Support\Facades\Log::info("WhatsApp alert triggered to {$waNumber} for ticket ID #{$ticket->id}: {$ticket->subject}");
            }
        }

        return $this->successResponse($ticket, 'Support ticket created successfully', 201);
    }

    /**
     * Checkout applying wallet balance if requested.
     */
    public function checkout(Request $request): JsonResponse
    {
        $validator = Validator::make($request->all(), [
            'listing_id' => 'required|exists:listings,id',
            'delivery_address' => 'required|array',
            'delivery_address.name' => 'required|string',
            'delivery_address.phone' => 'required|string',
            'delivery_address.street' => 'required|string',
            'delivery_address.city' => 'required|string',
            'delivery_address.state' => 'required|string',
            'delivery_address.pincode' => 'required|string|max:10',
            'use_wallet' => 'nullable|boolean',
        ]);

        if ($validator->fails()) {
            return $this->errorResponse('Validation error', 422, $validator->errors());
        }

        $listing = Listing::with('seller')->find($request->input('listing_id'));

        // Check if listing is active
        if ($listing->listing_status !== 'active') {
            return $this->errorResponse('Listing is not available for purchase.', 400);
        }

        // Check if buyer is not the seller
        if ($listing->seller->user_id === $request->user()->id) {
            return $this->errorResponse('You cannot buy your own listing.', 400);
        }

        // Check if listing is restricted to trusted/verified buyers only
        if ($listing->trusted_buyers_only && $request->user()->buyer_badge === 'new_buyer') {
            return $this->errorResponse('This seller requires Verified Buyer status. Complete 5+ purchases to unlock.', 400);
        }

        // Calculate pricing
        $productAmount = $listing->price;
        $shippingAmount = $listing->shipping_charges;
        $totalAmount = $productAmount + $shippingAmount;
        $commissionPercent = $listing->commission_rate;
        $commissionAmount = round(($productAmount * $commissionPercent) / 100, 2);
        $sellerPayoutAmount = $productAmount - $commissionAmount;

        $useWallet = $request->boolean('use_wallet');
        $walletAppliedAmount = 0.00;

        if ($useWallet) {
            $wallet = $request->user()->getWalletInstance();
            $walletBalance = (float) $wallet->balance;
            if ($walletBalance > 0) {
                $walletAppliedAmount = min($walletBalance, $totalAmount);
            }
        }

        $remainingAmount = $totalAmount - $walletAppliedAmount;
        $orderStatus = $remainingAmount <= 0 ? 'payment_received' : 'pending_payment';
        $razorpayOrderId = $remainingAmount > 0 ? 'order_' . Str::random(14) : null;

        $order = DB::transaction(function () use (
            $listing, $request, $productAmount, $shippingAmount, $totalAmount,
            $commissionPercent, $commissionAmount, $sellerPayoutAmount,
            $razorpayOrderId, $orderStatus, $walletAppliedAmount, $remainingAmount, $useWallet
        ) {
            $order = Order::create([
                'listing_id'             => $listing->id,
                'buyer_id'               => $request->user()->id,
                'seller_id'              => $listing->seller_id,
                'product_amount'         => $productAmount,
                'shipping_amount'        => $shippingAmount,
                'total_amount'           => $totalAmount,
                'commission_percent'     => $commissionPercent,
                'commission_amount'      => $commissionAmount,
                'seller_payout_amount'   => $sellerPayoutAmount,
                'razorpay_order_id'      => $razorpayOrderId,
                'wallet_amount_applied'  => $walletAppliedAmount,
                'order_status'           => $orderStatus,
                'delivery_address'       => $request->input('delivery_address'),
                'testing_window_days'    => $listing->testing_window_days,
                'warranty_terms_snapshot' => [
                    'manufacturer_warranty_status'  => $listing->manufacturer_warranty_status,
                    'manufacturer_warranty_months'  => $listing->manufacturer_warranty_months,
                    'seller_warranty_months'        => $listing->seller_warranty_months,
                    'document_status'               => $listing->document_status,
                ],
            ]);

            // Debit from wallet if any applied
            if ($walletAppliedAmount > 0) {
                $wallet = $request->user()->getWalletInstance();
                $wallet->debit(
                    $walletAppliedAmount,
                    'order_payment',
                    $order->id,
                    "Payment for Order #{$order->order_number}"
                );
            }

            // If fully paid, perform settlement and listing state change
            if ($orderStatus === 'payment_received') {
                // Update listing status
                $listing->update([
                    'listing_status' => 'sold',
                    'sold_at' => Carbon::now(),
                ]);

                // Create Escrow
                Escrow::create([
                    'order_id' => $order->id,
                    'amount_held' => $order->product_amount,
                    'seller_amount' => $order->seller_payout_amount,
                    'commission_amount' => $order->commission_amount,
                    'status' => 'held',
                    'payout_status' => 'pending',
                    'warranty_days' => $order->testing_window_days,
                ]);

                // Create Shipment skeleton
                Shipment::create([
                    'order_id' => $order->id,
                    'status' => 'pending',
                ]);

                // Send dynamic emails
                Notification::sendSystemMail($order->buyer, 'payment_success', [
                    'buyer_name' => $order->buyer->name,
                    'order_number' => $order->order_number,
                    'order_amount' => $order->total_amount,
                    'product_title' => $order->listing->title,
                    'seller_shop_name' => $order->seller->shop_name,
                ]);

                Notification::sendSystemMail($order->seller->user, 'escrow_hold', [
                    'seller_name' => $order->seller->user->name,
                    'buyer_name' => $order->buyer->name,
                    'order_number' => $order->order_number,
                    'product_title' => $order->listing->title,
                    'seller_payout_amount' => $order->seller_payout_amount,
                    'testing_days' => $order->testing_window_days,
                ]);
            }

            return $order;
        });

        if ($orderStatus === 'payment_received') {
            return $this->successResponse($order, 'Order checkout completed successfully using wallet.', 201);
        }

        return $this->successResponse($order, 'Order checkout initiated. Please proceed with payment.', 201);
    }
}
